import type { Metadata } from "next";
import "./globals.css";
import Header from "./[components]/Header";
import SubHeader from "./[components]/SubHeader";
import Footer from "./[components]/Footer";
import GoTop from "./[components]/GoTop";


export const metadata: Metadata = {
  title: "HD demoes",
  description: "Generated by next js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
        className={`antialiased py-[2.5%] md:py-10`}
      >
      
        <main className="mx-auto max-w-[1200px] w-[95%] bg-[#f7f7f7]  shadow-xl">
            <Header/>
      <SubHeader/>
        {children}
        <Footer/>
        <GoTop/>
        </main>
      </body>
    </html>
  );
}
